---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
patchesStrategicMerge:
  - deployment.yaml

namespace: default

commonLabels:
  build: $BUILD_HASH
  env: prd
images:
  - name: account-service
    newName: gcr.io/${PROJECT_NAME}/account-service
    digest: $(cat digest.txt)
